# Generated by Django 3.1.5 on 2021-01-21 20:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(editable=False, max_length=255, verbose_name='Пользователь')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефона необходимо вводить в формате "+78005553535"', regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book_data.book', verbose_name='Книга')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRequest',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('user', models.CharField(editable=False, max_length=255, verbose_name='Пользователь')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефона необходимо вводить в формате "+78005553535"', regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('date', models.DateTimeField(blank=True, editable=False, verbose_name='Дата заявки')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('book', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='book_data.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'historical request',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
